// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: create.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationPackage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DeviceTokens   []string               `protobuf:"bytes,2,rep,name=deviceTokens,proto3" json:"deviceTokens,omitempty"`
	AnalyticsLabel string                 `protobuf:"bytes,3,opt,name=analyticsLabel,proto3" json:"analyticsLabel,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Image          string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Data           map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationPackage) Reset() {
	*x = NotificationPackage{}
	mi := &file_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPackage) ProtoMessage() {}

func (x *NotificationPackage) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPackage.ProtoReflect.Descriptor instead.
func (*NotificationPackage) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationPackage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationPackage) GetDeviceTokens() []string {
	if x != nil {
		return x.DeviceTokens
	}
	return nil
}

func (x *NotificationPackage) GetAnalyticsLabel() string {
	if x != nil {
		return x.AnalyticsLabel
	}
	return ""
}

func (x *NotificationPackage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationPackage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationPackage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *NotificationPackage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationPackage   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationRequest) GetNotification() *NotificationPackage {
	if x != nil {
		return x.Notification
	}
	return nil
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_create_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_create_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_create_proto protoreflect.FileDescriptor

const file_create_proto_rawDesc = "" +
	"\n" +
	"\fcreate.proto\x12\rnotifications\"\xb6\x02\n" +
	"\x13NotificationPackage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\"\n" +
	"\fdeviceTokens\x18\x02 \x03(\tR\fdeviceTokens\x12&\n" +
	"\x0eanalyticsLabel\x18\x03 \x01(\tR\x0eanalyticsLabel\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12@\n" +
	"\x04data\x18\a \x03(\v2,.notifications.NotificationPackage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x13NotificationRequest\x12F\n" +
	"\fnotification\x18\x01 \x01(\v2\".notifications.NotificationPackageR\fnotification\"0\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2o\n" +
	"\x13NotificationService\x12X\n" +
	"\vSendMessage\x12\".notifications.NotificationRequest\x1a#.notifications.NotificationResponse\"\x00B\x1eZ\x1cgo-noti-server/notificationsb\x06proto3"

var (
	file_create_proto_rawDescOnce sync.Once
	file_create_proto_rawDescData []byte
)

func file_create_proto_rawDescGZIP() []byte {
	file_create_proto_rawDescOnce.Do(func() {
		file_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_create_proto_rawDesc), len(file_create_proto_rawDesc)))
	})
	return file_create_proto_rawDescData
}

var file_create_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_create_proto_goTypes = []any{
	(*NotificationPackage)(nil),  // 0: notifications.NotificationPackage
	(*NotificationRequest)(nil),  // 1: notifications.NotificationRequest
	(*NotificationResponse)(nil), // 2: notifications.NotificationResponse
	nil,                          // 3: notifications.NotificationPackage.DataEntry
}
var file_create_proto_depIdxs = []int32{
	3, // 0: notifications.NotificationPackage.data:type_name -> notifications.NotificationPackage.DataEntry
	0, // 1: notifications.NotificationRequest.notification:type_name -> notifications.NotificationPackage
	1, // 2: notifications.NotificationService.SendMessage:input_type -> notifications.NotificationRequest
	2, // 3: notifications.NotificationService.SendMessage:output_type -> notifications.NotificationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_create_proto_init() }
func file_create_proto_init() {
	if File_create_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_create_proto_rawDesc), len(file_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_create_proto_goTypes,
		DependencyIndexes: file_create_proto_depIdxs,
		MessageInfos:      file_create_proto_msgTypes,
	}.Build()
	File_create_proto = out.File
	file_create_proto_goTypes = nil
	file_create_proto_depIdxs = nil
}
